### ISSUE TITLE
Improving the search functionality

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#49]
I'm finding that the search field is working very inconsistently for me. Most of the time I receive a message that reads "We couldn't find any results that matched your search criteria."

Many of the words in a listing don't seem to be searchable through the search field such as host name (first or last) and keywords.

I searched for a word in two experience listings right next to each other: one generated a result and one didn't. Then I searched for a keyword with the one that had generated a result but they keyword didn't generate a result (see screenshots)

<img width="1055" alt="screen shot 2015-12-30 at 3 38 32 pm" src="https://cloud.githubusercontent.com/assets/14365107/12059227/48bea362-af0c-11e5-8665-300f368204f2.png">

**Comment by samuelreh** [comment]
I changed the index so it does a full re build every 10 minutes. Seems to be working for me now. Hopefully it doesn't get out of sync now.

**Comment by jonaspiet** [comment]
Same issue happens, when searching for words copied from the description, the title or tags.
Sometimes no experiences show up, sometimes some. 

This is a direct issue, as we need to be able to filter for experiences that have a high availability. We're planning to make them with a  ' * ' in the title.

**Comment by samuelreh** [comment]
Search should be working again now. It indexes every 10 minutes (at 5:01, 5:11, 5:21, 5:31...). So if a listing is changed, it might not be searchable until the next indexing.

**Comment by AndieFro** [comment]
This is still not functioning very well. Trying to search for the Cake Decorating experience and searching for Cake shows nothing, 'Cake' is in the title and tags. 

Also, this experience is not coming up in the 'food' category. I've double checked that it's listed under the category 'food'.

**Comment by samuelreh** [comment]
k sorry about that should be fixed now.
