### ISSUE TITLE
bug: editing welcome email from admin area - no go

### ISSUE THREAD

**Issue by lisajoytrick** [InWithForward/sharetribe#86]
I noticed all the image urls are broken in the welcome email and went to fix them and got a strange screen.

here's the screenshot.
<img width="963" alt="screen shot 2016-02-01 at 2 42 16 pm" src="https://cloud.githubusercontent.com/assets/14365107/12733872/20d77e28-c8f2-11e5-9e43-2ae592bba198.png">

**Comment by samuelreh** [comment]
Yup, sorry, should be fixed now.

**Comment by lisajoytrick** [comment]
This is still a problem for me. I've tried safari and chrome on my macbook.

**Comment by samuelreh** [comment]
Hey, sorry bout that. This breaks when I deploy from staging as opposed to straight from my computer (which I forget about sometimes). It should work now.
